# Generated by Django 3.0.3 on 2020-02-11 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('vat_number', models.CharField(max_length=32)),
                ('vat_applicable', models.BooleanField(default=True)),
                ('iban', models.CharField(blank=True, max_length=255)),
                ('bic', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=255)),
                ('country_code', models.CharField(choices=[('BE', 'Belgium'), ('CN', 'China'), ('DE', 'Germany'), ('FR', 'France'), ('HK', 'Hong Kong'), ('NL', 'The Netherlands'), ('PL', 'Poland'), ('US', 'United States of America')], default='BE', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
