# Generated by Django 3.0.3 on 2020-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_rate',
            field=models.CharField(choices=[('HR', 'Hourly Rate'), ('FD', 'Flat Daily Rate'), ('PR', 'Per-Project Basis')], default='HR', max_length=2),
        ),
    ]
