# Generated by Django 3.0.3 on 2020-02-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_billing_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=255)),
                ('country_code', models.CharField(choices=[('BE', 'Belgium'), ('CN', 'China'), ('DE', 'Germany'), ('FR', 'France'), ('HK', 'Hong Kong'), ('NL', 'The Netherlands'), ('PL', 'Poland'), ('US', 'United States of America')], default='BE', max_length=2)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
