# Generated by Django 3.0.3 on 2020-02-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='main_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_contact', to='customers.CustomerContact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='timesheet_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_contact', to='customers.CustomerContact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercontact',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
