# Generated by Django 3.0.3 on 2020-02-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200211_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='main_contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='timesheet_contact',
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
            preserve_default=False,
        ),
    ]
