# Generated by Django 3.0.3 on 2020-02-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200211_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='contact_type',
            field=models.CharField(choices=[('TC', 'Timesheet Contact'), ('IC', 'Invoicing Contact'), ('BT', 'Backup Timesheet Contact'), ('BI', 'Backup Invoicing Contact'), ('TL', 'Teamlead'), ('BT', 'Backup Teamlead'), ('LM', 'Line Manager'), ('BL', 'Backup Line Manager'), ('EC', 'Emergency Contact')], default='TC', max_length=2),
        ),
    ]
